### ISSUE TITLE
'Experiment' level DOI minting

### ISSUE THREAD

**Issue by millercathy** [modc08/modc08#10]

**Comment by franksc** [comment]
Re #12 – when a DOI is minted for an experiment this should trigger the minting of a DOI for each dataset in the experiment that does not already have a DOI recorded.

Where a dataset already has a DOI recorded, probably because it is also part of another experiment that has been previously published, a second DOI should not be minted.

**Comment by Li-ReDBox** [comment]
https://github.com/modc08/mytardis/commit/452bd3e762f38a5acce17502412ec9a1e3e8f47c has the basic code to mint included datasets which do not have DOI yet.

**Comment by franksc** [comment]
Testing:

When an experiment is set to public:
- [x] DOI is minted

For each child dataset of experiment:
- [ ] DOI is minted – __minted and recorded against dataset, but not showing in dataset view__
- [x] ... unless dataset already has a DOI (from being part of previously published experiment)

**Comment by franksc** [comment]
Closing this as minted DOIs are definitely being recorded against datasets – dataset view to be extended to display DOIs as part of #5.
