### ISSUE TITLE
Implement DOI minting at dataset level

### ISSUE THREAD

**Issue by millercathy** [modc08/modc08#12]
Metadata to be determined - see #11

**Comment by Li-ReDBox** [comment]
https://github.com/modc08/mytardis/commit/030c157915caf200489889068dcbdb878a1a83a2

When DOI was successfully minted, __immutable__ of the dataset is set, mytardis' existing code disables editing interfaces: adding files, editing dataset

Currently, the function is implemented in editing function with an extra form property: *publish*. When editing a dataset, if *publish* is checked, saving will mint this dataset. (https://github.com/modc08/mytardis/commit/ba0795387fed5204c57eaf4134d1f95ddc744515#diff-9c280283d91f0d9a13150840db91899d)

To make it more obvious, I temporarily changed the content of editing button to: Edit Dataset Description, Mint DOI. (https://github.com/modc08/mytardis/commit/ba0795387fed5204c57eaf4134d1f95ddc744515#diff-d6c08722fae5c8de8695a27b1d170bef). Please advise the proper text for the button.

**Comment by franksc** [comment]
See https://github.com/modc08/modc08/issues/10#issuecomment-70771350 re making an experiment public triggering DOI minting for child datasets

**Comment by franksc** [comment]
Re #11: Minting DOI for a dataset should for the DataCite 'title' field use the value of Dataset.description, but per https://github.com/modc08/mytardis/blob/develop-doi/tardis/tardis_portal/ands_doi.py#L198 it is currently using ```ex.title``` i.e. the title of the parent experiment. Should be ```self.obj.description``` I think

**Comment by Li-ReDBox** [comment]
Dataset's description is used as its title when it is being minted: https://github.com/modc08/mytardis/commit/6750ee3ac149a9c78bbbcb0e4c0372b34f595360

**Comment by franksc** [comment]
Tested 30 Jan vm-develop-doi-20150130-155609:
- [x] Dataset's description is used as its title when it is being minted

**Comment by Li-ReDBox** [comment]
#### FYI: 
Re my previous comment:
_When DOI was successfully minted, immutable of the dataset is set, mytardis' existing code disables editing interfaces: adding files, editing dataset_

dataset_write_perm checks if __immutable__ attribute is set: https://github.com/modc08/mytardis/blob/modc08/tardis/tardis_portal/auth/decorators.py#L126

In contrast, experiment_write_perm does not check __locked__ attribute: https://github.com/modc08/mytardis/blob/modc08/tardis/tardis_portal/auth/decorators.py#L209

Also, change_perm = write_perm.

**Comment by franksc** [comment]
It is fudgy for a dataset to determine its 'direct parent' experiment, from which it should derive some metadata like authors and publication year, based on looking up the chronologically earliest of its set of parent experiments. This is particularly the case when a dataset minting its DOI is only ever triggered following the action of a experiment minting its DOI – at this point in time it is known which experiment a DOI should be using for its 'direct parent'.

@Li-ReDBox can you please change DOI minting functionality so:

- When an experiment minting a DOI triggers attempted minting of DOIs for its child datasets, this passes the experiment as a parameter to method/object involved in attempting to mint DOI for a dataset ('hey child dataset, mint a DOI for yourself using me as your parent experiment')

- Rather than looking up its earliest parent experiment, dataset uses this passed experiment for looking up metadata e.g. institution_name, publication_year

- Add to Dataset model a foreign key to Experiment where this 'direct parent' relationship can be recorded for later use (e.g. in displaying citation for dataset)

**Comment by Li-ReDBox** [comment]
Here is the commit for this issue: https://github.com/modc08/mytardis/commit/0b647f2c2eb15b1389864dc1eeb237772bf0b859

When a dataset is created, it records which experiment it is in. Later, when shared, if the containing experiment is being published, this is updated to that experiment.

No lookup/guess any more

**Comment by franksc** [comment]
Testing:

- Create 'Early test experiment with DS1'
- Create dataset DS1 and attach to this experiment
    - DS1.experiment = 'Early test experiment with DS1' :white_check_mark: 
- Create another experiment 'Later test experiment with DS1'
- Attach DS1 to this experiment
    - Verify DS1.experiment still 'Early test experiment with DS1' :white_check_mark: 
- Go into 'Later test experiment with DS1' and make public/mint DOI
    - DS1.experiment now 'Later test experiment with DS1' :white_check_mark: 
- Create 'Third experiment with DS1', attach DS1
- Make public/mint DOI for 'Third experiment with DS1'
   - DS1.experiment unchanged :white_check_mark:

**Comment by franksc** [comment]
Have also confirmed that in minting a DOI dataset looks up metadata from the direct rather than chronologically earliest experiment.
