### ISSUE TITLE
Metadata downloads with files

### ISSUE THREAD

**Issue by millercathy** [modc08/modc08#36]
Hi @franksc Do you have further info on this? Thanks.

**Comment by franksc** [comment]
To enhance reuse of data obtained via the MODC08 repository, a dataset downloaded as a tar/archive should include a file containing all pipeline/provenance metadata associated with the dataset.

@craigpatten re #40 this file will need to be inserted/included in the tar file also including files retrieved from the HCP

Metadata to be included:
- the Analysis record associated with the dataset
- All Processing records referencing that Analysis record
- Chain of Sequence, Library, Extract records referencing each Processing record
- Sample and Source records referencing each Extract record

All metadata fields in these models should be included, except for a small set of fields in Source and Sample (refer 'Publicly displayed' column in the metadata schema).

For bonus points we might like to export this metadata in some machine-readable format (JSON, XML, YAML, ... ?), either in addition or instead of a plain text representation.

**Comment by franksc** [comment]
One way to maybe do this:
1. Prepare a plain text template based on existing [block template](https://github.com/modc08/mytardis/blob/modc08/tardis/apps/acad/templates/dataset.html) which lists provenance and pipeline metadata for a given dataset
2. Use Django's render_to_string() to get a string-y render of this template for target dataset
3. Insert this as a file (filename 'metadata.txt' is probably good enough) into streamed tar file (cf. #40) at time of generation

For downloading a tar of an entire experiment, we want each dataset subdirectory (cf. #44) to have its own metadata.txt

**Comment by craigpatten** [comment]
Basic structure at modc08/mytardis@80032d6474210dc32b45ede6776bc8da3a843ac3.

@Li-ReDBox can make something more useful out of this! 😊

**Comment by franksc** [comment]
I will prepare a template and we can take it from there

**Comment by Li-ReDBox** [comment]
@franksc: the proposal is simple, efficient and should work fine with a similar template as you mentioned for the format you want (if in html and the exact content, the change will be minimal :laughing: ) and calling render_to_string with that template in @craigpatten's [code](https://github.com/modc08/mytardis/commit/80032d6474210dc32b45ede6776bc8da3a843ac3).

My rough test with my understanding of this task:

``` shell
diff --git a/tardis/tardis_portal/download.py b/tardis/tardis_portal/download.py
index 184149f..805fcbf 100644
--- a/tardis/tardis_portal/download.py
+++ b/tardis/tardis_portal/download.py
@@ -41,6 +41,7 @@ from tardis.tardis_portal.views import return_response_not_found, \
     return_response_error

 from tardis.apps.acad.models import Analysis
+from django.template.loader import render_to_string

 import datetime
 import threading
@@ -411,7 +412,7 @@ def _streaming_tar_thread(directory, downloads, out):
         analysis = Analysis.objects.get(dataset=dataset_id)
         # insert human-readable text file containing ACAD metadata
         # perhaps generate from a template?
-        metadata = "insert the metadata here!\n"
+        metadata = render_to_string('tar_meta.html', {'dataset' : dataset})
         tarobj = tarfile.TarInfo(name="%s/%s/metadata.txt" % (directory, dataset))
         tarobj.mode = 0644
         tarobj.size = len(metadata)
```

**Comment by franksc** [comment]
Done (modc08/mytardis@416a618ddb60a84bcbcf59b3b5a611b66dd271dc)
