### ISSUE TITLE
Search results display

### ISSUE THREAD

**Issue by millercathy** [modc08/modc08#37]
Searching will encompass Experiments, Datasets & Source/Sample views - see #33 
How will these different results be presented?
Further investigation required.
Cc @shundezhang

**Comment by franksc** [comment]
Dependent on #6

**Comment by millercathy** [comment]
@franksc sketch out mock ups for consideration by ACAD

**Comment by franksc** [comment]
A random example ...

Let's say a hypothetical end user is really interested in ancient human skulls found in Africa, so in the single search box (cf. #34) they enter 'Africa skull'.

If the repository data contains:
- a Source 'Source1234' which has among other properties .geoloc_continent='africa' and .source_details='skull'
- an Experiment with title 'ACAD African skulls study'

we would expect the results list to be:
- Source 1234 <-- linked to view for this Source
- ACAD African skulls study <-- linked to view for this Experiment

**Comment by millercathy** [comment]
@franksc Sounds reasonable to me. Would any datasets derived from the source also be listed in the results? Or would the user simply browse to them from the returned Source?

**Comment by franksc** [comment]
A first draft mockup of a search results page (returned after user has executed a search query):

# Search results for *search query*

*x* experiments | *y* sources

[**Experiment title**]() (*YYYY*) [MyTardis badge *x* datasets] [MyTardis badge *y* files]
Author One, Author Two, Author Three
Experiment description

[**Source name**]()
[Some metadata not included in source name e.g. 'Infant male aged 25-30 years, carbon date 7205 ± 50']
Samples: Tooth (upper left molar), tooth (lower right canine)

Datasets from this source: [Dataset 1234](), [Dataset 5678]()

**Comment by franksc** [comment]
Just to clarify, by 'MyTardis badge' I mean these things you see in various browse views: 
![screen shot 2015-02-17 at 17 22 04](https://cloud.githubusercontent.com/assets/8837821/6224284/94718112-b6c9-11e4-8b10-78f5f0fbca33.png)

**Comment by shundezhang** [comment]
I have added a new variable in setting.py to use a customised single search view. Therefore all acad-related search view/form/indexes are kept in the acad app. This is easier to modify in the future since we have everything in one place. The result page is finished according to the above mockup (except the link to source page because it is work-in-progress).

**Comment by franksc** [comment]
Can we:
- Group search results under headings 'Experiments' and 'Sources'
  - If no results for a result type (Experiment or Source) retrieved, don't include the heading
- In the _x_ experiments | _y_ sources line, link '_x_ experiments' and '_y_ sources' to the corresponding headings
- Only show '_x_ experiments' or '_y_ sources' if number of results for the result type >=1. I.e. if 0 experiments and 3 sources retrieved, show '3 sources' rather than '0 experiments | 3 sources'

**Comment by shundezhang** [comment]
Fixed in the above commit

**Comment by franksc** [comment]
:+1:

**Comment by franksc** [comment]
Made some display tweaks in modc08/mytardis@a3721345976ec123ee8388c9a3aac87500fac04f . Will reopen this issue if further tweaks required.
