### ISSUE TITLE
Stream individual objects from the object store

### ISSUE THREAD

**Issue by craigpatten** [modc08/modc08#39]
As per #31.

**Comment by craigpatten** [comment]
[ above change due to the use of content-based addressing in the object store and the HCP's apparent refusal to honour response-content-disposition in the same way as [S3](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html) ]

**Comment by craigpatten** [comment]
Done as of https://github.com/modc08/mytardis/commit/875bcc4b3b7b753ccf291e2bfe7af060df645e82.

**Comment by franksc** [comment]
There seems to be an issue with accessing data files via MyTardis when end user is not logged in but instead viewing a private experiment by way of a time-limited access URL (you can generate these in MyTardis in Experiment view -> Sharing tab -> Create New Temporary Link).

Using one of these 'secret' links a non-authenticated user can view a private experiment and its datasets, but when trying to download a data file they get nothing/a blank page.

Could this be because the corresponding data blob is set to private in the object store bucket, and as end user is not actually authenticated in MyTardis they rightly shouldn't be able to get to it?

**Comment by craigpatten** [comment]
Putting in a request here for the fresh pairs of eyes of @shundezhang and @Li-ReDBox to look at this one. 😊

Background: viewing an experiment with a private sharing link (i.e. token=X query parameter) sets up an appropriate session which authorises these guests to view datasets, download tar files, etc. That all works.

However, when attempting to download a single file from the dataset view, [DataFileResource.download_file](/modc08/mytardis/blob/modc08/tardis/tardis_portal/api.py#L724) thinks that the user is not authenticated and therefore denies the download. Downloading tar files goes through [different code](/modc08/mytardis/blob/modc08/tardis/tardis_portal/download.py) and doesn't seem to suffer from this problem.

**Comment by craigpatten** [comment]
PS the issue doesn't seem to be anything to do with using the object store as a backend. This auth problem crops up before the code even has a chance to interact with the object store to construct its response.

**Comment by franksc** [comment]
FYI this problem also appears to affect MyTardis release 3.6

**Comment by craigpatten** [comment]
Interesting! I'll admit it was fairly late the other night when I tried vanilla MT and thought (?) that it was immune, but if you've seen it break then I'll take your word for it. 😊

**Comment by franksc** [comment]
Grischa at MyTardis HQ is looking into a fix for this

**Comment by franksc** [comment]
Fixed in MyTardis core by Grischa: https://github.com/mytardis/mytardis/commit/e732af715b236023667e5db21504ae27d72c78db

Applied to our fork: https://github.com/modc08/mytardis/commit/1c408d6

:+1:
