### ISSUE TITLE
Prod DOI minting

### ISSUE THREAD

**Issue by millercathy** [modc08/modc08#55]
Set up prod DOI registration as per http://ands.org.au/services/cmd-technical-document.pdf section 3.1.B.
Agreement already signed. Need to add new IP addresses?

**Comment by franksc** [comment]
I don't think the IP addresses associated with the Cite My Data appid are important because we are using appid + shared secret, rather than appid + IP address, for authentication.

Also, we may need to update the domain to whatever site URL we end up with (cf. #48) if it's different to what was supplied during the test registration.

**Comment by millercathy** [comment]
Good points. Thanks @franksc.
