### ISSUE TITLE
Test 16 - Minting DOI for metadata only - DOI success msg but DOI does not appear

### ISSUE THREAD

**Issue by millercathy** [modc08/modc08#80]
Hi @Li-ReDBox 
I'm trying to mint a DOI for a Study following these steps:
Study exists - Go to Sharing Tab - Change Public Access option - Select Public Metadata Only - Select licence - Select Confirm 
The success message appears but no DOI is recorded in the metadata. The DOI does not appear to have been minted.
If you want details of which build I am using, email me. I don't want to put the url in here.
Cheers
Cathy

**Comment by Li-ReDBox** [comment]
Hi @millercathy,

Not sure if this is related to another open [issue](https://github.com/modc08/modc08/issues/64). If you was running test, it could be in the production setup which probably has some issues around DOI at the moment. @franksc might comment on this to give more information.

**Comment by millercathy** [comment]
Hi @Li-ReDBox No, it's not related to that issue.
It seems to be an issue with DOIs not minting. Can you please test? See if you can replicate? @franksc will send URL and details via email. Thank you!

**Comment by franksc** [comment]
From what I could observe over @millercathy's shoulder during testing, after submitting licence options form the experiment showed updated licence and sharing options but DOI was not minted and experiment not locked.

DOI minting and locking of experiment (or dataset) is handled by methods in ands_doi.py . This is initiated by `ensure_doi_exists()` in models/hooks.py, which relies on a Django [`post_save` signal](https://docs.djangoproject.com/en/1.5/ref/signals/#django.db.models.signals.post_save) to be called when an Experiment object is saved.

So, it sounds like the issue here is the `post_save` signal is not being sent or received correctly under some circumstances.

Maybe try moving the `ensure_doi_exists()` code into `Experiment.save()`?

**Comment by Li-ReDBox** [comment]
@franksc, I was going to suggest the same thing. If you check the log, sometimes there are two doi come in at the same time, yet, Experiment instance was not updated with doi. But quite often, there is no trace of doi signal.

Also, in Experiment's save() function, there is a publication function [call](https://github.com/modc08/mytardis/blob/modc08/tardis/tardis_portal/models/experiment.py#L81). One more will not hurt in my view.

**Comment by Li-ReDBox** [comment]
A branch has  been create for tackling this problem. Basically, signal were not sent or received sometimes in production setting which gives a false impression DOI has been minted. This [commit](https://github.com/modc08/mytardis/commit/3ec1bcf075be5fe0ee92ec8d211ac543e49ff1a6) removed the signal sending and moved minting into Experiment save function.

Also there is a very rough [busy wheel displayed when minting](https://github.com/modc08/mytardis/commit/56249607cb4d8e5b81fd4638ab800a26565e5683). This is not intended to be a proper solution. It serves as a starting point and test to see if this procedure is necessary.

**Comment by franksc** [comment]
@Li-ReDBox and I have tested these changes and have been unable to reproduce this error.

Assuming the root issue was the Experiment post-save signal not being sent or received in some instances, moving the DOI minting call into Experiment.save() should have worked around it.
